/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package programta;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.File;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Locale;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import programta.Controller.*;
import programta.Entity.*;

/**
 *
 * @author Nadiya
 */
public class InterfaceTA extends javax.swing.JFrame {

    CInterfaceManager interface_manager;
    ArrayList<ECuaca> data_cuaca;
    String Data;
   
    public InterfaceTA() {
        initComponents();
        interface_manager = new CInterfaceManager();
        
        btn_loadfile.setEnabled(true);
        ComboBox_metode.setEnabled(false);
        TextFieldJumPopulasi.setEnabled(false);
        TextFieldJumIterasi.setEnabled(false);
        TextFieldCrossoverRate.setEnabled(false);
        TextFieldMutationRate.setEnabled(false);
        btn_hasilprediksi.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextField_folderPath = new javax.swing.JTextField();
        btn_loadfile = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TextFieldJumPopulasi = new javax.swing.JTextField();
        TextFieldJumIterasi = new javax.swing.JTextField();
        TextFieldCrossoverRate = new javax.swing.JTextField();
        TextFieldMutationRate = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btn_hasilprediksi = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbl_datacuaca = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lbl_hasil_akurasi = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBox_metode = new javax.swing.JComboBox<>();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PREDIKSI CUACA");

        jLabel2.setText("Dataset");

        TextField_folderPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_folderPathActionPerformed(evt);
            }
        });

        btn_loadfile.setText("Load File");
        btn_loadfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loadfileActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Jumlah Populasi  ");

        jLabel11.setText("Jumlah Iterasi   ");

        jLabel12.setText("crossover rate");

        jLabel13.setText("mutation rate   ");

        TextFieldJumPopulasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldJumPopulasiKeyTyped(evt);
            }
        });

        TextFieldJumIterasi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldJumIterasiKeyTyped(evt);
            }
        });

        TextFieldCrossoverRate.setDoubleBuffered(true);
        TextFieldCrossoverRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldCrossoverRateKeyTyped(evt);
            }
        });

        TextFieldMutationRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextFieldMutationRateKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldMutationRate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldCrossoverRate, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextFieldJumIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(TextFieldJumPopulasi, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(TextFieldJumPopulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TextFieldJumIterasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(TextFieldCrossoverRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(TextFieldMutationRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel3.setText("Tabel Hasil Prediksi Sistem");

        btn_hasilprediksi.setText("Hasil Prediksi");
        btn_hasilprediksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hasilprediksiActionPerformed(evt);
            }
        });

        jPanel5.setAutoscrolls(true);

        tbl_datacuaca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Tanggal", "Suhu", "Kelembaban", "Tekanan Udara", "Kecepatan Angin", "Kondisi Cuaca", "Prediksi Sistem"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbl_datacuaca);
        if (tbl_datacuaca.getColumnModel().getColumnCount() > 0) {
            tbl_datacuaca.getColumnModel().getColumn(0).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(0).setPreferredWidth(30);
            tbl_datacuaca.getColumnModel().getColumn(1).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(2).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(2).setPreferredWidth(50);
            tbl_datacuaca.getColumnModel().getColumn(3).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(3).setPreferredWidth(70);
            tbl_datacuaca.getColumnModel().getColumn(4).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(4).setPreferredWidth(90);
            tbl_datacuaca.getColumnModel().getColumn(5).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(5).setPreferredWidth(90);
            tbl_datacuaca.getColumnModel().getColumn(6).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(7).setResizable(false);
            tbl_datacuaca.getColumnModel().getColumn(7).setPreferredWidth(90);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_hasilprediksi)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_hasilprediksi)
                .addGap(18, 18, 18))
        );

        jLabel4.setText("Akurasi Sistem :");

        lbl_hasil_akurasi.setText("-");

        jLabel6.setText("Parameter Algoritma Genetika");

        jLabel7.setText("Pilih Metode          ");

        ComboBox_metode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fuzzy Mamdani", "Algoritma Genetika + Mamdani" }));
        ComboBox_metode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_metodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_hasil_akurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextField_folderPath, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(btn_loadfile))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ComboBox_metode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_folderPath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btn_loadfile))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_metode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(lbl_hasil_akurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 858, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_loadfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loadfileActionPerformed
        String path;
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Excel FILES", "xlsx","Excel");
        chooser.setFileFilter(filter);
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Select File");
        
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            String selectedFolder = String.valueOf(chooser.getSelectedFile());
            TextField_folderPath.setText(selectedFolder);
            System.out.println("getSelectedFile() : " + selectedFolder);
            
            File selectedFile = chooser.getSelectedFile();
            path = selectedFile.getAbsolutePath();
            
            ComboBox_metode.setEnabled(true);
            btn_hasilprediksi.setEnabled(true);
            
            data_cuaca = new ArrayList();

            data_cuaca = interface_manager.load_file_excel(path);

            DefaultTableModel cuaca_model = (DefaultTableModel) tbl_datacuaca.getModel();

            String[] data = new String[7];
            for (int i = tbl_datacuaca.getRowCount() - 1; i >= 0; i--) {
                cuaca_model.removeRow(i);
            }

            for (int i = 0; i < data_cuaca.size(); i++) {
                data[0] = String.valueOf((int) data_cuaca.get(i).getNo());
                data[1] = data_cuaca.get(i).getTanggal();
                data[2] = String.valueOf(data_cuaca.get(i).getSuhu());
                data[3] = String.valueOf(data_cuaca.get(i).getKelembaban());
                data[4] = String.valueOf(data_cuaca.get(i).getTekananUdara());
                data[5] = String.valueOf(data_cuaca.get(i).getKecepatanAngin());
                data[6] = data_cuaca.get(i).getResult();

                cuaca_model.addRow(data);
            }
            
        } else {
            JOptionPane.showMessageDialog(this, "GAGAL MEMUAT DATA");
        }
    }//GEN-LAST:event_btn_loadfileActionPerformed

    private void TextField_folderPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_folderPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_folderPathActionPerformed
    

    private void TextFieldJumPopulasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldJumPopulasiKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        if (TextFieldJumPopulasi.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldJumPopulasiKeyTyped

    private void TextFieldJumIterasiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldJumIterasiKeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if (!(Character.isDigit(enter))) {
            evt.consume();
        }
        if (TextFieldJumIterasi.getText().length() >= 2) {
            evt.consume();
        }
    }//GEN-LAST:event_TextFieldJumIterasiKeyTyped

    private void TextFieldCrossoverRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldCrossoverRateKeyTyped
        // TODO add your handling code here:
//        char c = evt.getKeyChar();
//        
//        DoubleNumbersKeyListener DKL = new DoubleNumbersKeyListener();
//        if (!DKL.valid_keys.contains(c)) {
//            evt.consume();
//        } else {
//            if (c == KeyEvent.VK_DELETE || c == KeyEvent.VK_BACK_SPACE) {
//                if (!DKL.sequence.isEmpty()) {
//                    char last = DKL.sequence.remove(DKL.sequence.size() - 1);
//                    if (last == '.') {
//                        DKL.valid_keys.add(last);
//                    }
//                }
//            } else {
//                DKL.sequence.add(c);
//                if (c == '.') {
//                    DKL.valid_keys.remove(c);
//                }
//            }
//        }
    }//GEN-LAST:event_TextFieldCrossoverRateKeyTyped

    private void TextFieldMutationRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextFieldMutationRateKeyTyped
        // TODO add your handling code here:
//        char enter = evt.getKeyChar();
//        if (!(Character.isDigit(enter))) {
//            evt.consume();
//        }

    }//GEN-LAST:event_TextFieldMutationRateKeyTyped

    private boolean check_parameter() {
        boolean flag;

        if (TextFieldJumPopulasi.getText().isEmpty() || TextFieldJumIterasi.getText().isEmpty() || TextFieldCrossoverRate.getText().isEmpty() || TextFieldMutationRate.getText().isEmpty()) {
            flag = true;
        } else {
            flag = false;
        }
        return flag;
    }

    private void btn_hasilprediksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hasilprediksiActionPerformed
        // TODO add your handling code here:
        String[] hasil_prediksi;
        int pilihan = ComboBox_metode.getSelectedIndex();
        NumberFormat format = NumberFormat.getInstance(Locale.GERMAN);
        
        if (pilihan == 0) {
            System.out.println("Pilih Fuzzy Mamdani");
            interface_manager.do_fuzzy_mamdani();
            hasil_prediksi = interface_manager.getHasilPrediksi();
            
            DefaultTableModel cuaca_model = (DefaultTableModel) tbl_datacuaca.getModel();

            String[] data = new String[8];
            for (int i = tbl_datacuaca.getRowCount() - 1; i >= 0; i--) {
                cuaca_model.removeRow(i);
            }

            for (int i = 0; i < data_cuaca.size(); i++) {
                data[0] = String.valueOf((int) data_cuaca.get(i).getNo());
                data[1] = data_cuaca.get(i).getTanggal();
                data[2] = String.valueOf(data_cuaca.get(i).getSuhu());
                data[3] = String.valueOf(data_cuaca.get(i).getKelembaban());
                data[4] = String.valueOf(data_cuaca.get(i).getTekananUdara());
                data[5] = String.valueOf(data_cuaca.get(i).getKecepatanAngin());
                data[6] = data_cuaca.get(i).getResult();
                data[7] = hasil_prediksi[i];

                cuaca_model.addRow(data);
            }
            
            lbl_hasil_akurasi.setText(String.valueOf(interface_manager.getHasilAkurasi())+"%");
            
        } else {
            System.out.println("Pilih Algen+Mamdani");
            if (check_parameter() == false) {
                int jum_populasi = Integer.parseInt(TextFieldJumPopulasi.getText());
                int jum_iterasi = Integer.parseInt(TextFieldJumIterasi.getText());
                double cr = Double.parseDouble(TextFieldCrossoverRate.getText());
                double mr = Double.parseDouble(TextFieldMutationRate.getText());
                interface_manager.do_algenfuzzy(jum_iterasi, jum_populasi, cr, mr);
                hasil_prediksi = interface_manager.getHasilPrediksiHybrid();
            
                DefaultTableModel cuaca_model = (DefaultTableModel) tbl_datacuaca.getModel();

                String[] data = new String[8];
                for (int i = tbl_datacuaca.getRowCount() - 1; i >= 0; i--) {
                    cuaca_model.removeRow(i);
                }

                for (int i = 0; i < data_cuaca.size(); i++) {
                    data[0] = String.valueOf((int) data_cuaca.get(i).getNo());
                    data[1] = data_cuaca.get(i).getTanggal();
                    data[2] = String.valueOf(data_cuaca.get(i).getSuhu());
                    data[3] = String.valueOf(data_cuaca.get(i).getKelembaban());
                    data[4] = String.valueOf(data_cuaca.get(i).getTekananUdara());
                    data[5] = String.valueOf(data_cuaca.get(i).getKecepatanAngin());
                    data[6] = data_cuaca.get(i).getResult();
                    data[7] = hasil_prediksi[i];

                    cuaca_model.addRow(data);
                }

            } else {
                JOptionPane.showMessageDialog(null, "Parameter Belum Diisi", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btn_hasilprediksiActionPerformed

    private void ComboBox_metodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_metodeActionPerformed
        int pilihan = ComboBox_metode.getSelectedIndex();
            if (pilihan == 0) {
                TextFieldJumPopulasi.setEnabled(false);
                TextFieldJumIterasi.setEnabled(false);
                TextFieldCrossoverRate.setEnabled(false);
                TextFieldMutationRate.setEnabled(false);
            }
            else {
                TextFieldJumPopulasi.setEnabled(true);
                TextFieldJumIterasi.setEnabled(true);
                TextFieldCrossoverRate.setEnabled(true);
                TextFieldMutationRate.setEnabled(true);
            }
    }//GEN-LAST:event_ComboBox_metodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceTA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceTA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_metode;
    private javax.swing.JTextField TextFieldCrossoverRate;
    private javax.swing.JTextField TextFieldJumIterasi;
    private javax.swing.JTextField TextFieldJumPopulasi;
    private javax.swing.JTextField TextFieldMutationRate;
    private javax.swing.JTextField TextField_folderPath;
    private javax.swing.JButton btn_hasilprediksi;
    private javax.swing.JButton btn_loadfile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbl_hasil_akurasi;
    private javax.swing.JTable tbl_datacuaca;
    // End of variables declaration//GEN-END:variables

}
